// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.openshift.notebook.core.domain;

public class ProfileBuilder extends ProfileBuilderBase<ProfileBuilder> {
	public static ProfileBuilder profile() {
		return new ProfileBuilder();
	}

	public ProfileBuilder() {
		super(new Profile());
	}

	public Profile build() {
		return getInstance();
	}
}

class ProfileBuilderBase<GeneratorT extends ProfileBuilderBase<GeneratorT>> {
	private Profile instance;

	protected ProfileBuilderBase(Profile aInstance) {
		instance = aInstance;
	}

	protected Profile getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withEmail(String aValue) {
		instance.setEmail(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPassword(String aValue) {
		instance.setPassword(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withActive(boolean aValue) {
		instance.setActive(aValue);

		return (GeneratorT) this;
	}
}
